package com.okayjam.web.service.entity;

public class TbTest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_test.id
     *
     * @mbg.generated Wed Aug 15 19:25:50 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_test.key
     *
     * @mbg.generated Wed Aug 15 19:25:50 CST 2018
     */
    private String key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_test.value
     *
     * @mbg.generated Wed Aug 15 19:25:50 CST 2018
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_test.id
     *
     * @return the value of tb_test.id
     *
     * @mbg.generated Wed Aug 15 19:25:50 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_test.id
     *
     * @param id the value for tb_test.id
     *
     * @mbg.generated Wed Aug 15 19:25:50 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_test.key
     *
     * @return the value of tb_test.key
     *
     * @mbg.generated Wed Aug 15 19:25:50 CST 2018
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_test.key
     *
     * @param key the value for tb_test.key
     *
     * @mbg.generated Wed Aug 15 19:25:50 CST 2018
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_test.value
     *
     * @return the value of tb_test.value
     *
     * @mbg.generated Wed Aug 15 19:25:50 CST 2018
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_test.value
     *
     * @param value the value for tb_test.value
     *
     * @mbg.generated Wed Aug 15 19:25:50 CST 2018
     */
    public void setValue(String value) {
        this.value = value;
    }
}