package com.okayjam.web.core.dao;

import com.okayjam.web.core.entity.TbTest;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;

import java.util.List;
@Mapper
public interface TbTestMapper {

    // 查询全部
    @Select("SELECT * FROM tb_test")
    List<TbTest> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbg.generated Wed Aug 15 19:25:50 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbg.generated Wed Aug 15 19:25:50 CST 2018
     */
    int insert(TbTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbg.generated Wed Aug 15 19:25:50 CST 2018
     */
    int insertSelective(TbTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbg.generated Wed Aug 15 19:25:50 CST 2018
     */
    TbTest selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbg.generated Wed Aug 15 19:25:50 CST 2018
     */
    int updateByPrimaryKeySelective(TbTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbg.generated Wed Aug 15 19:25:50 CST 2018
     */
    int updateByPrimaryKey(TbTest record);
}